### ISSUE TITLE
Issue with expman

### ISSUE THREAD

**Issue by ganatma** [fabiocarrara/cbigan-ad#1]
The Experiment class in the experiment.py file misses some methods like ckpt, require_csv. I am using the following link to get the expman repo "https://github.com/fabiocarrara/expman". 

The link given for expman on the cbigan-ad repo gives a 404 error

Thanks a lot for your help on this.

**Comment by fabiocarrara** [comment]
thanks for reporting, I've updated the reference to the expman submodule.
