### ISSUE TITLE
the AUC of test data is Strange

### ISSUE THREAD

**Issue by chen-linxin** [fabiocarrara/cbigan-ad#2]
![Uploading image.png…]()
when I train the model ,I found that the AUC  was the highest at the beginnings .Have you encountered this problem?

**Comment by fabiocarrara** [comment]
In my runs, the highest AUC usually occurs later in the training phase. Which category are you considering in your run?
Also, try again uploading the image you attached; I cannot visualize it.

**Comment by chen-linxin** [comment]
<img width="177" alt="carpet-auc" src="https://user-images.githubusercontent.com/72249950/146909662-5d30d48f-8adb-4f77-821a-b8070ecc71a9.PNG">
What I train is  the Carpet class .  I'm sorry that there may be a problem with the way I uploaded the picture before, can you see it now?

**Comment by fabiocarrara** [comment]
Actually, in the Carpet class, the peak AUC comes earlier than usual also in my runs, but it does not drop drastically later as in yours. Here's my AUC plot for Carpet:
![](https://user-images.githubusercontent.com/7997320/146945517-3d7d00d0-1819-4eac-896f-2c2681dd4abd.png)

**Comment by chen-linxin** [comment]
I change the batch size from 16 to 32,and now the auc is look like yours.
I will find the reason why a smaller bs will cause this result.
thank you for your help!
